
development:

  adapter: mysql2
  database: lyric_server
  host: 106.187.102.167
  encoding: utf8
  username: root
  password: "010883"
  pool: 25

  
  # adapter: mysql2
  # database: lyric_server
  # host: 127.0.0.1
  # encoding: utf8
  # username: root
  # password: "db"
  # pool: 25

test:
  adapter: mysql2
  database: lyric_server
  host: 127.0.0.1
  encoding: utf8
  username: root
  password: "db"

production:
  adapter: mysql2
  database: lyric_server
  host: 127.0.0.1
  encoding: utf8
  username: root
  password: "db"
